image: python

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - python --version

.acquire-project-dependencies:
  before_script:
    - pip install -r requirements.txt


# Columns of the pipeline
stages:
  - build
  - test
  - deploy

# test installation
install:
  stage: build
  extends:
    - .acquire-project-dependencies
  script:
    - pip install .

# Static code analysis job via Pylint
static analysis:
  stage: test
  before_script:
    - pip install pylint
  extends:
    - .acquire-project-dependencies
  script:
    - pylint bdld
  allow_failure: true

# run all unittests
unittests:
  stage: test
  extends:
    - .acquire-project-dependencies
  script:
    - python3 -m unittest discover

# code coverage reporting
module tests:
  stage: test
  before_script:
    - pip install coverage
  extends:
    - .acquire-project-dependencies
  script:
    - coverage run -m unittest discover > /dev/null
    - coverage report
  coverage: /\d+\%\s*$/

# Test building package (make package)
package:
  stage: deploy
  before_script:
    - pip install wheel
  extends:
    - .acquire-project-dependencies
  script:
    - python setup.py sdist bdist_wheel