image: python

variables:
  GIT_SUBMODULE_STRATEGY: recursive

default:
    before_script:
    - pip install -r requirements.txt

# Columns of the pipeline
stages:
  - build
  - test
  - deploy

# test installation
install:
  stage: build
  script:
    - pip install .

# Static code analysis job via Pylint
static analysis:
  stage: test
  before_script:
    - pip install pylint
  script:
    - pylint bdld
  allow_failure: true

# run all unittests
unittests:
  stage: test
  script:
    - python3 -m unittest discover

# code coverage reporting
module tests:
  stage: test
  before_script:
    - pip install coverage
  script:
    - coverage run -m unittest discover > /dev/null
    - coverage report
  coverage: /\d+\%\s*$/

# Test building package (make package)
package:
  stage: deploy
  before_script:
   - pip install wheel
  script:
    - python setup.py sdist bdist_wheel